######################################################################
# Automatically generated by qmake (2.01a) So 19. Dez 18:44:48 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += colorizer.h Julia.h
SOURCES += colorizer.cpp Julia.cpp main.cpp
RC_FILE += resources.rc
RESOURCES += resources.qrc